export const productsFetched = 'productsFetched'
export const addedToCart = 'addedToCart'
export const removedFromCart = 'removedFromCart'
export const cartUpdated = 'cartUpdated'
export const lightboxToggled = 'lightboxToggled'
export const menuToggled = 'menuToggled'